fail_fast: false
default_language_version:
    python: python3.7
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-docstring-first
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: double-quote-string-fixer
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
  - id: check-symlinks
  - id: check-json
  - id: check-added-large-files
  - id: no-commit-to-branch
  - id: requirements-txt-fixer
