language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  # - pipenv run coverage run manage.py test --no-input --debug-mode -v 2
  - pipenv run coverage html -d public/coverage
  - pipenv run coverage report -m
